[workspace]
members = [
    "octocat-rs",
    "github-rest",
    "examples/basic",
    "examples/basic-secret",
    "examples/commitsummary",
    "examples/cloudflare",
]
default-members = ["octocat-rs", "github-rest"]
