[package]
name = "github-rest"
version = "0.0.0"
edition = "2021"
authors = [
    "Proudmuslim <proudmuslim-dev@protonmail.com>",
    "Tricked <tricked@duck.com>",
]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
## HTTP
github-api = { git = "https://github.com/octocat-rs/github-api" }

## Serialization/Deserialization
strum = { version = "0.23", features = ["derive"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"

# Misc
async-trait = "0.1.52"
paste = "1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
reqwest = { version = "0.11.8" }

[target.'cfg(target_family = "wasm")'.dependencies]
worker = "0.0.9"


[features]
default = ["builders"]
full = ["builders", "client"]
builders = []
client = []


[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
