[package]
name = "octocat-rs"
version = "0.0.0"
edition = "2021"
authors = [
    "Proudmuslim <proudmuslim-dev@protonmail.com>",
    "Tricked <tricked@duck.com>",
]
license = "MIT OR Apache-2.0"
description = """
(WIP) A GitHub API client.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
## GitHub
github-rest = { path = "../github-rest" }
github-api = { git = "https://github.com/octocat-rs/github-api" }

## Async
tokio = { version = "1", features = ["full"], optional = true }
async-trait = "0.1.52"
futures = "0.3"

## Webserver
warp = { version = "0.3", optional = true }

## Serialization/Deserialization
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
toml = "0.5.8"

## Error Handling
thiserror = "1.0.30"
anyhow = "1.0.51"

## Util
strum_macros = "0.23"
reqwest = { version = "^0.11.8", optional = true }
strum = "0.23.0"
worker = { version = "0.0.9", optional = true }
serde_urlencoded = { version = "0.7.1", optional = true }
base64 = { version = "0.13.0", optional = true }
hmac = { version = "0.12.1", optional = true }
sha2 = { version = "0.10.2", optional = true }

[features]
default = [ "native" ]
native = ["warp", "tokio", "reqwest"]
workers = ["worker", "serde_urlencoded", "base64", "hmac", "sha2"]
