[alias]
d = "doc"
t = "test --all-targets --features full" # Many tests are failing, this is intentional and can be ignored
r = "run --package basic"
rr = "run --release --package basic"
# space_example = ["run", "--release", "--", "\"command list\""]

[build]
rustdoc = "rustdoc"
rustdocflags = ["--default-theme=ayu"]
