[alias]
b = "build --all-targets"
c = "clippy --tests --all-targets"
d = "doc"
t = "test --all-targets"
r = "run --package basic"
rr = "run --release --package basic"
# space_example = ["run", "--release", "--", "\"command list\""]

[build]
rustdoc = "rustdoc"
rustdocflags = ["--default-theme=ayu"]

